{ config, lib, pkgs, flakePath ? null, ... }:

with lib;

let
  # Determine flake path: use provided path or fallback to common locations
  effectiveFlakePath = 
    if flakePath != null then flakePath
    else if builtins.pathExists "/etc/nixos/flake.nix" then "/etc/nixos"
    else if builtins.pathExists "${config.home.homeDirectory}/nix/flake.nix" then "${config.home.homeDirectory}/nix"
    else "${config.home.homeDirectory}/.config/nixos";
in

{
  options.home.profiles.development = {
    enable = mkEnableOption "development tools profile";

    devShells = {
      enable = mkEnableOption "generic development shells" // { default = true; };
      enableLaunchers = mkEnableOption "shell launcher scripts" // { default = true; };
      enableDirenvTemplates = mkEnableOption "direnv templates" // { default = true; };
    };

    editors = {
      vscode.enable = mkEnableOption "Visual Studio Code";
      neovim.enable = mkEnableOption "Neovim with LazyVim" // { default = true; };
    };
  };

  config = mkIf config.home.profiles.development.enable {
    # Enable development programs
    programs.git.enable = true;
    programs.neovim.enable = config.home.profiles.development.editors.neovim.enable;
    
    # Essential development tools
    home.packages = with pkgs;
      # Always included
      [
        # Version control
        git
        gh
        lazygit
        tig

        # Terminal tools
        tmux
        zoxide
        fzf

        # Text processing
        jq
        yq-go

        # Build essentials
        gnumake
        cmake

        # Docker
        docker-compose
      ]
      ++
      # VSCode (optional - choose one)
      (optionals config.home.profiles.development.editors.vscode.enable [
        vscodium  # Open source version without Microsoft telemetry
        # vscode  # Official Microsoft version - use if you need proprietary extensions
      ]);

    # ========================================================================
    # Dev Shell Integration (Conditional)
    # ========================================================================

    # Enable direnv integration
    programs.direnv = mkIf config.home.profiles.development.devShells.enable {
      enable = true;
      nix-direnv.enable = true;

      config = {
        global = {
          warn_timeout = "30s";
        };
      };
    };

    # Create launcher scripts and direnv templates
    home.file = mkMerge [
      # Launcher scripts
      (mkIf (config.home.profiles.development.devShells.enable &&
             config.home.profiles.development.devShells.enableLaunchers) {

        ".local/bin/dev-python" = {
          executable = true;
          text = ''
            #!/usr/bin/env bash
            echo "🐍 Launching Python development shell..."
            nix develop ${toString effectiveFlakePath}#python
          '';
        };

        ".local/bin/dev-node" = {
          executable = true;
          text = ''
            #!/usr/bin/env bash
            echo "🟢 Launching Node.js development shell..."
            nix develop ${toString effectiveFlakePath}#node
          '';
        };

        ".local/bin/dev-rust" = {
          executable = true;
          text = ''
            #!/usr/bin/env bash
            echo "🦀 Launching Rust development shell..."
            nix develop ${toString effectiveFlakePath}#rust
          '';
        };

        ".local/bin/dev-go" = {
          executable = true;
          text = ''
            #!/usr/bin/env bash
            echo "🐹 Launching Go development shell..."
            nix develop ${toString effectiveFlakePath}#go
          '';
        };
      })

      # Direnv templates
      (mkIf (config.home.profiles.development.devShells.enable &&
             config.home.profiles.development.devShells.enableDirenvTemplates) {

        ".config/direnv/templates/python.envrc".text = ''
          # Python development environment
          # Auto-generated by NixOS configuration
          use flake ${toString effectiveFlakePath}#python
        '';

        ".config/direnv/templates/node.envrc".text = ''
          # Node.js development environment
          # Auto-generated by NixOS configuration
          use flake ${toString effectiveFlakePath}#node
        '';

        ".config/direnv/templates/rust.envrc".text = ''
          # Rust development environment
          # Auto-generated by NixOS configuration
          use flake ${toString effectiveFlakePath}#rust
        '';

        ".config/direnv/templates/go.envrc".text = ''
          # Go development environment
          # Auto-generated by NixOS configuration
          use flake ${toString effectiveFlakePath}#go
        '';

        ".config/direnv/templates/README.md".text = ''
          # Direnv Templates

          Automatically generated from NixOS configuration.

          ## Quick Setup

          Copy a template to your project directory:

          ```bash
          cp ~/.config/direnv/templates/python.envrc .envrc
          direnv allow
          ```

          The development shell will automatically activate when you `cd` into the directory!

          ## Available Templates

          - **python.envrc** - Python 3.12 + data science tools
          - **node.envrc** - Node.js 22 + npm/yarn/pnpm
          - **rust.envrc** - Rust toolchain + rust-analyzer
          - **go.envrc** - Go + gopls

          ## Manual Usage

          You can also launch shells directly:

          ```bash
          dev-python   # Quick launcher
          dev-node     # Quick launcher
          dev-rust     # Quick launcher
          dev-go       # Quick launcher
          ```

          Or use nix develop:

          ```bash
          nix develop ${toString effectiveFlakePath}#python
          ```
        '';
      })
    ];
  };
}

