{ config, lib, pkgs, ... }:

###############################################################################
# apollo — Top-level NixOS configuration
#
# This file imports all category modules and sets global defaults.
# To disable a service category, comment out its import below.
###############################################################################
{
  imports = [
    # hardware-configuration.nix is auto-generated by nixos-generate-config.
    # After first boot on the target machine, run:
    #   nixos-generate-config --root /
    # then copy /etc/nixos/hardware-configuration.nix here and uncomment:
    # ./hardware-configuration.nix

    # New modules (created as part of the migration)
    ./hardening.nix   # systemd service hardening presets
    ./backup.nix      # restic backups
  ];

  # ---------------------------------------------------------------------------
  # Nix settings
  # ---------------------------------------------------------------------------
  nix = {
    # Enable flakes and the new nix command
    settings = {
      experimental-features = [ "nix-command" "flakes" ];

      # Auto-optimise the store to save disk space via hard-links
      auto-optimise-store = true;

      # Trust wheel users to perform nix operations
      trusted-users = [ "root" "@wheel" ];

      # Build parallelism: auto-detect cores
      max-jobs = "auto";
      cores = 0;  # 0 = use all available cores

      # Use binary caches to reduce local builds
      builders-use-substitutes = true;

      # Additional caches
      extra-substituters = [
        "https://nix-community.cachix.org"
      ];
      extra-trusted-public-keys = [
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      ];

      # Keep at least 10 GiB free on /nix/store partition
      min-free = 10 * 1024 * 1024 * 1024;  # 10 GiB
      max-free = 200 * 1024 * 1024 * 1024; # 200 GiB
    };

    # Weekly garbage collection, keep last 30 days of generations
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 30d";
    };
  };

  # Allow unfree packages (Plex, unrar, etc.)
  nixpkgs.config.allowUnfree = true;

  # ---------------------------------------------------------------------------
  # Boot & Kernel
  # ---------------------------------------------------------------------------
  boot = {
    # Use latest kernel for Intel N100 (Alder Lake-N) i915 GPU support
    kernelPackages = pkgs.linuxPackages_latest;

    # Kernel modules needed early for NVMe + USB-attached storage
    initrd.availableKernelModules = [
      "nvme" "xhci_pci" "usb_storage" "uas" "ahci"
    ];

    # N100 does not fully support VT-d — prevent IOMMU errors
    kernelParams = [ "intel_iommu=off" ];

    # Clean /tmp on boot
    tmp.cleanOnBoot = true;
  };

  # ---------------------------------------------------------------------------
  # Hardware / GPU
  # ---------------------------------------------------------------------------
  hardware = {
    # Intel GPU acceleration for Plex transcoding & Immich ML
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver       # VA-API hardware encode/decode
        intel-compute-runtime    # OpenCL support
        vaapiIntel               # Legacy VA-API
        vaapiVdpau               # VDPAU → VA-API bridge
        libvdpau-va-gl           # VDPAU → VA-API/OpenGL bridge
      ];
    };

    # Enable all firmware
    enableRedistributableFirmware = true;
  };

  # ---------------------------------------------------------------------------
  # System
  # ---------------------------------------------------------------------------
  system = {
    stateVersion = "24.11";  # DO NOT CHANGE after first install

    # Auto-upgrade — downloads and applies updates automatically
    autoUpgrade = {
      enable = true;
      flags = [ "--no-update-lock-file" ];
      dates = "05:00";  # 5 AM daily
      randomizedDelaySec = "45min";
      allowReboot = true;  # actually apply updates (was false = download only)
    };
  };

  # ---------------------------------------------------------------------------
  # Locale & Time
  # ---------------------------------------------------------------------------
  time.timeZone = "Europe/Madrid";
  i18n = {
    defaultLocale = "en_US.UTF-8";
    extraLocaleSettings = {
      LC_TIME = "en_GB.UTF-8";
      LC_MONETARY = "es_ES.UTF-8";
    };
  };

  # ---------------------------------------------------------------------------
  # Networking basics (extended in networking.nix)
  # ---------------------------------------------------------------------------
  networking = {
    hostName = "apollo";
    networkmanager.enable = true;  # manages enp1s0 (DHCP from current netplan)
  };

  # ---------------------------------------------------------------------------
  # Security basics
  # ---------------------------------------------------------------------------
  security = {
    # Unprivileged user namespaces (needed by podman, chromium, etc.)
    unprivilegedUserns.enable = true;

    # sudo without password for wheel group (convenience for home server)
    sudo.execWheelOnly = true;
  };

  # ---------------------------------------------------------------------------
  # Systemd OOM killer — prevent RAM exhaustion on 16 GB system
  # ---------------------------------------------------------------------------
  systemd.oomd = {
    enable = true;
    # Kill the biggest memory hogs when system is under pressure
    extraConfig = {
      DefaultMemoryPressureDurationSec = "20s";
    };
  };

  # ---------------------------------------------------------------------------
  # sops-nix — Secrets management
  #
  # Before deploying, create the age key and encrypt secrets:
  #   1. mkdir -p ~/.config/sops/age
  #   2. age-keygen -o ~/.config/sops/age/keys.txt
  #   3. Copy the public key to .sops.yaml
  #   4. Encrypt each secret: sops secrets/<name>.yaml
  #
  # Secrets are decrypted to /run/secrets/<name> at boot.
  # Each module references config.sops.secrets.<name>.path to get the file path.
  # ---------------------------------------------------------------------------
  sops = {
    # Path to the age key file on the server
    defaultSopsFile = ./secrets/secrets.yaml;
    age.keyFile = "/home/jpolo/.config/sops/age/keys.txt";

    # Secret definitions used across modules
    # Each module defines its own secrets (see databases.nix, networking.nix, etc.)
  };

  # ---------------------------------------------------------------------------
  # Podman (container runtime, configured in individual service files)
  # ---------------------------------------------------------------------------
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;       # `docker` CLI compatibility alias
    dockerSocket.enable = true; # /run/podman/podman.sock for tools expecting docker socket

    # Create a default network for containers
    defaultNetwork.settings = {
      subnet = "10.88.0.0/16";
    };
  };

  # Enable OCI containers support (used by all service files)
  virtualisation.oci-containers.backend = "podman";

  # ---------------------------------------------------------------------------
  # Environment packages (available to all users)
  # ---------------------------------------------------------------------------
  environment.systemPackages = with pkgs; [
    # System tools
    htop btop neofetch lm_sensors pciutils usbutils
    hdparm smartmontools  # disk utilities

    # Networking
    curl wget bind-utils  # dnsutils (dig)
    tcpdump iperf3 netcat-gnu

    # File tools
    unzip p7zip unrar rar
    rsync rclone

    # Terminal & shell
    git vim tmux kitty.terminfo
  ];
}
