{ config, pkgs, lib, ... }:

with lib;

{
  config = mkIf config.home.profiles.desktop.enable {
    programs.kitty = {
      enable = true;
      
      # Font configuration
      font = {
        name = "JetBrains Mono";
        size = 12;
      };
      
      settings = {
        # Window settings
        background_opacity = "0.9";
        window_padding_width = 8;
        
        # Cursor
        cursor_shape = "beam";
        cursor_blink_interval = 0;
        
        # Performance
        repaint_delay = 10;
        input_delay = 3;
        sync_to_monitor = "yes";
      };
      
      # Include matugen-generated colors
      extraConfig = ''
        # Matugen color sync
        include ${config.xdg.configHome}/matugen/kitty.conf
      '';
    };
    
    # Configure matugen to generate kitty colors
    xdg.configFile."matugen/templates/kitty.conf" = {
      text = ''
        # Kitty color scheme generated by matugen
        foreground {{colors.on_surface.default.hex}}
        background {{colors.surface.default.hex}}
        selection_foreground {{colors.on_primary.default.hex}}
        selection_background {{colors.primary.default.hex}}
        
        # Cursor
        cursor {{colors.primary.default.hex}}
        cursor_text_color {{colors.on_primary.default.hex}}
        
        # URL underline color
        url_color {{colors.tertiary.default.hex}}
        
        # Tab bar colors
        active_tab_foreground {{colors.on_primary_container.default.hex}}
        active_tab_background {{colors.primary_container.default.hex}}
        inactive_tab_foreground {{colors.on_surface_variant.default.hex}}
        inactive_tab_background {{colors.surface_container.default.hex}}
        
        # Terminal colors
        color0 {{colors.surface_dim.default.hex}}
        color1 {{colors.error.default.hex}}
        color2 {{colors.tertiary.default.hex}}
        color3 {{colors.secondary.default.hex}}
        color4 {{colors.primary.default.hex}}
        color5 {{colors.primary_container.default.hex}}
        color6 {{colors.tertiary_container.default.hex}}
        color7 {{colors.on_surface.default.hex}}
        
        # Bright colors
        color8 {{colors.surface_bright.default.hex}}
        color9 {{colors.error.default.hex}}
        color10 {{colors.tertiary.default.hex}}
        color11 {{colors.secondary.default.hex}}
        color12 {{colors.primary.default.hex}}
        color13 {{colors.primary_container.default.hex}}
        color14 {{colors.tertiary_container.default.hex}}
        color15 {{colors.on_surface_variant.default.hex}}
      '';
    };
  };
}

