# This file was generated by the initial setup and will be replaced
# by `nixos-generate-config` when apollo is first deployed.
#
# Run on apollo hardware:
#   nixos-generate-config --root /
# Then copy /etc/nixos/hardware-configuration.nix here.
#
# For now, storage mounts are defined in modules/services/homelab/storage.nix
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme" "xhci_pci" "usb_storage" "uas" "ahci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # NOTE: File systems are defined in modules/services/homelab/storage.nix
  # The actual hardware-configuration will be generated on the target machine.
  # After running nixos-generate-config, merge the boot/loader info here
  # and keep storage mounts in the homelab/storage module.
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/PLACEHOLDER";
    fsType = "ext4";
    options = [ "defaults" ];
  };

  # Swap (also defined in storage.nix, but this is needed for boot)
  swapDevices = [ ];
}